export const transactionsMockData = [
  { date: "Oct 15, 2025", description: "Freelance Project", category: "Deposit", type: "Income", amount: "$500.00" },
  { date: "Oct 12, 2025", description: "Groceries", category: "Food", type: "Expense", amount: "$80.00" },
  { date: "Oct 10, 2025", description: "Water bill", category: "Utility", type: "Expense", amount: "$40.00" },
  { date: "Oct 9, 2025", description: "Work", category: "Paycheck", type: "Income", amount: "$2380.00" },
  { date: "Oct 3, 2025", description: "Friend send money", category: "Venmo", type: "Income", amount: "$180.00" },
  { date: "Oct 2, 2025", description: "Subway", category: "Food", type: "Expense", amount: "$20.00" },
  { date: "Oct 16, 2025", description: "Amazon Purchase", category: "Shopping", type: "Expense", amount: "$55.00" },
  { date: "Oct 17, 2025", description: "Netflix", category: "Subscription", type: "Expense", amount: "$16.99" },
  { date: "Oct 18, 2025", description: "Gas Station", category: "Transport", type: "Expense", amount: "$45.00" },
  { date: "Oct 18, 2025", description: "Work Bonus", category: "Paycheck", type: "Income", amount: "$300.00" },
  { date: "Oct 19, 2025", description: "Coffee Shop", category: "Food", type: "Expense", amount: "$8.50" },
  { date: "Oct 20, 2025", description: "Rent Payment", category: "Housing", type: "Expense", amount: "$950.00" },
  { date: "Oct 20, 2025", description: "Client Payment", category: "Deposit", type: "Income", amount: "$1200.00" },
  { date: "Oct 21, 2025", description: "Movie Tickets", category: "Entertainment", type: "Expense", amount: "$25.00" },
  { date: "Oct 21, 2025", description: "Gym Membership", category: "Health", type: "Expense", amount: "$35.00" },
  { date: "Oct 22, 2025", description: "YouTube Premium", category: "Subscription", type: "Expense", amount: "$11.99" },
  { date: "Oct 22, 2025", description: "Paycheck", category: "Salary", type: "Income", amount: "$2400.00" },
  { date: "Oct 23, 2025", description: "Groceries", category: "Food", type: "Expense", amount: "$95.00" },
  { date: "Oct 23, 2025", description: "Electric Bill", category: "Utility", type: "Expense", amount: "$70.00" },
  { date: "Oct 24, 2025", description: "Tax Refund", category: "Deposit", type: "Income", amount: "$450.00" },
  { date: "Oct 25, 2025", description: "Spotify", category: "Subscription", type: "Expense", amount: "$9.99" },
  { date: "Oct 25, 2025", description: "Dinner Out", category: "Food", type: "Expense", amount: "$60.00" },
  { date: "Oct 26, 2025", description: "Client Invoice", category: "Freelance", type: "Income", amount: "$600.00" },
  { date: "Oct 27, 2025", description: "Laundry", category: "Home", type: "Expense", amount: "$15.00" },
  { date: "Oct 27, 2025", description: "Work Lunch", category: "Food", type: "Expense", amount: "$12.00" },
  { date: "Oct 28, 2025", description: "Interest Earned", category: "Bank", type: "Income", amount: "$5.50" },
  { date: "Oct 29, 2025", description: "Online Course", category: "Education", type: "Expense", amount: "$40.00" },
  { date: "Oct 29, 2025", description: "Uber Ride", category: "Transport", type: "Expense", amount: "$18.00" },
  { date: "Oct 30, 2025", description: "Gift from Friend", category: "Venmo", type: "Income", amount: "$100.00" },
  { date: "Oct 31, 2025", description: "Halloween Snacks", category: "Food", type: "Expense", amount: "$25.00" },
  { date: "Nov 1, 2025", description: "Phone Bill", category: "Utility", type: "Expense", amount: "$50.00" },
  { date: "Nov 2, 2025", description: "Paycheck", category: "Salary", type: "Income", amount: "$2400.00" },
  { date: "Nov 3, 2025", description: "Grocery Store", category: "Food", type: "Expense", amount: "$78.00" },
  { date: "Nov 3, 2025", description: "Freelance Payment", category: "Deposit", type: "Income", amount: "$350.00" },
  { date: "Nov 4, 2025", description: "Pet Food", category: "Pets", type: "Expense", amount: "$30.00" },
  { date: "Nov 5, 2025", description: "Health Insurance", category: "Health", type: "Expense", amount: "$100.00" },
  { date: "Nov 6, 2025", description: "Gas Station", category: "Transport", type: "Expense", amount: "$40.00" },
  { date: "Nov 7, 2025", description: "Etsy Sale", category: "Side Hustle", type: "Income", amount: "$75.00" },
  { date: "Nov 8, 2025", description: "Restaurant", category: "Food", type: "Expense", amount: "$55.00" },
  { date: "Nov 8, 2025", description: "Streaming Subscription", category: "Subscription", type: "Expense", amount: "$14.99" },
  { date: "Nov 9, 2025", description: "Internet Bill", category: "Utility", type: "Expense", amount: "$65.00" },
  { date: "Nov 9, 2025", description: "Work Bonus", category: "Salary", type: "Income", amount: "$500.00" },
  { date: "Nov 10, 2025", description: "Grocery Store", category: "Food", type: "Expense", amount: "$85.00" },
  { date: "Nov 10, 2025", description: "PayPal Transfer", category: "Venmo", type: "Income", amount: "$90.00" },
  { date: "Nov 11, 2025", description: "Concert Ticket", category: "Entertainment", type: "Expense", amount: "$120.00" },
  { date: "Nov 12, 2025", description: "Gym", category: "Health", type: "Expense", amount: "$25.00" },
  { date: "Nov 12, 2025", description: "Freelance Design", category: "Freelance", type: "Income", amount: "$250.00" },
  { date: "Nov 13, 2025", description: "Car Insurance", category: "Transport", type: "Expense", amount: "$110.00" },
  { date: "Nov 14, 2025", description: "Dinner Out", category: "Food", type: "Expense", amount: "$70.00" },
  { date: "Nov 15, 2025", description: "Freelance Project", category: "Deposit", type: "Income", amount: "$400.00" },
  { date: "Nov 15, 2025", description: "Electric Bill", category: "Utility", type: "Expense", amount: "$60.00" },
  { date: "Nov 16, 2025", description: "Spotify", category: "Subscription", type: "Expense", amount: "$9.99" },
  { date: "Nov 17, 2025", description: "Salary", category: "Paycheck", type: "Income", amount: "$2400.00" },
  { date: "Nov 18, 2025", description: "Fast Food", category: "Food", type: "Expense", amount: "$15.00" },
  { date: "Nov 18, 2025", description: "Freelance Job", category: "Freelance", type: "Income", amount: "$320.00" },
  { date: "Nov 19, 2025", description: "Amazon Order", category: "Shopping", type: "Expense", amount: "$65.00" },
  { date: "Nov 20, 2025", description: "Gas", category: "Transport", type: "Expense", amount: "$35.00" },
  { date: "Nov 21, 2025", description: "Paycheck", category: "Salary", type: "Income", amount: "$2400.00" },
  { date: "Nov 22, 2025", description: "Electric Bill", category: "Utility", type: "Expense", amount: "$72.00" },
  { date: "Nov 22, 2025", description: "Tax Refund", category: "Deposit", type: "Income", amount: "$600.00" },
  { date: "Nov 23, 2025", description: "Dinner Out", category: "Food", type: "Expense", amount: "$50.00" },
  { date: "Nov 24, 2025", description: "Spotify", category: "Subscription", type: "Expense", amount: "$9.99" },
  { date: "Nov 24, 2025", description: "Freelance Payment", category: "Freelance", type: "Income", amount: "$420.00" },
  { date: "Nov 25, 2025", description: "Gift", category: "Venmo", type: "Income", amount: "$150.00" },
  { date: "Nov 26, 2025", description: "Groceries", category: "Food", type: "Expense", amount: "$80.00" },
  { date: "Nov 26, 2025", description: "Electric Bill", category: "Utility", type: "Expense", amount: "$75.00" },
  { date: "Nov 27, 2025", description: "Client Invoice", category: "Freelance", type: "Income", amount: "$300.00" },
  { date: "Nov 27, 2025", description: "Water Bill", category: "Utility", type: "Expense", amount: "$35.00" },
  { date: "Nov 28, 2025", description: "Fuel", category: "Transport", type: "Expense", amount: "$45.00" },
  { date: "Nov 29, 2025", description: "Freelance Payment", category: "Deposit", type: "Income", amount: "$500.00" },
  { date: "Nov 30, 2025", description: "Fast Food", category: "Food", type: "Expense", amount: "$12.00" },
  { date: "Dec 1, 2025", description: "Paycheck", category: "Salary", type: "Income", amount: "$2400.00" },
  { date: "Dec 2, 2025", description: "Netflix", category: "Subscription", type: "Expense", amount: "$16.99" },
  { date: "Dec 3, 2025", description: "Groceries", category: "Food", type: "Expense", amount: "$85.00" },
  { date: "Dec 4, 2025", description: "Water Bill", category: "Utility", type: "Expense", amount: "$40.00" },
  { date: "Dec 5, 2025", description: "Work Bonus", category: "Salary", type: "Income", amount: "$350.00" },
  { date: "Dec 6, 2025", description: "Gift from Friend", category: "Venmo", type: "Income", amount: "$120.00" },
  { date: "Dec 7, 2025", description: "Electric Bill", category: "Utility", type: "Expense", amount: "$70.00" },
  { date: "Dec 8, 2025", description: "Gas", category: "Transport", type: "Expense", amount: "$30.00" },
  { date: "Dec 9, 2025", description: "Freelance Job", category: "Freelance", type: "Income", amount: "$300.00" },
  { date: "Dec 10, 2025", description: "Restaurant", category: "Food", type: "Expense", amount: "$45.00" },
  { date: "Dec 11, 2025", description: "Internet Bill", category: "Utility", type: "Expense", amount: "$65.00" },
  { date: "Dec 12, 2025", description: "Spotify", category: "Subscription", type: "Expense", amount: "$9.99" },
  { date: "Dec 13, 2025", description: "Paycheck", category: "Salary", type: "Income", amount: "$2400.00" },
  { date: "Dec 14, 2025", description: "Groceries", category: "Food", type: "Expense", amount: "$90.00" },
  { date: "Dec 15, 2025", description: "Electric Bill", category: "Utility", type: "Expense", amount: "$68.00" },
  { date: "Dec 16, 2025", description: "Freelance Payment", category: "Deposit", type: "Income", amount: "$400.00" },
  { date: "Dec 17, 2025", description: "Dinner Out", category: "Food", type: "Expense", amount: "$60.00" },
  { date: "Dec 18, 2025", description: "Gas", category: "Transport", type: "Expense", amount: "$38.00" },
  { date: "Dec 19, 2025", description: "Netflix", category: "Subscription", type: "Expense", amount: "$16.99" },
  { date: "Dec 20, 2025", description: "Client Invoice", category: "Freelance", type: "Income", amount: "$500.00" },
  { date: "Dec 21, 2025", description: "Water Bill", category: "Utility", type: "Expense", amount: "$40.00" },
  { date: "Dec 22, 2025", description: "Grocery Store", category: "Food", type: "Expense", amount: "$75.00" },
  { date: "Dec 23, 2025", description: "Paycheck", category: "Salary", type: "Income", amount: "$2400.00" },
  { date: "Dec 24, 2025", description: "Holiday Gift", category: "Shopping", type: "Expense", amount: "$100.00" },
  { date: "Dec 25, 2025", description: "Christmas Bonus", category: "Deposit", type: "Income", amount: "$800.00" },
  { date: "Dec 26, 2025", description: "Dinner Out", category: "Food", type: "Expense", amount: "$85.00" },
  { date: "Dec 27, 2025", description: "Internet Bill", category: "Utility", type: "Expense", amount: "$65.00" },
  { date: "Dec 28, 2025", description: "Freelance Project", category: "Freelance", type: "Income", amount: "$500.00" },
  { date: "Dec 29, 2025", description: "Groceries", category: "Food", type: "Expense", amount: "$90.00" },
  { date: "Dec 30, 2025", description: "PayPal Transfer", category: "Venmo", type: "Income", amount: "$100.00" },
  { date: "Dec 31, 2025", description: "New Year Party", category: "Entertainment", type: "Expense", amount: "$120.00" }
];